var settings = {
  "socket_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbiI6IkRFMDhFOTQ4QjdFRTFBNzcwRjBBIiwicmVhZF9vbmx5Ijp0cnVlLCJwcmV2ZW50X21hc3RlciI6dHJ1ZSwidHdpdGNoX2lkIjoiMjYxOTc5NTkifQ.0kJX4Rd8USk_UYizxrAXRurFOeGCBgU8Q7C_z5Ccb9I",
  "followMessage": "@{0} Thank you for the Follow!",
  "newSubMessage": "We got a new Squirrel in the Family. Thank You {0} for your support!",
  "reSubMessage": "{0} resubscribed for {1} months total!",
  "wbSubMessage": "{0} resubscribed. Welcome back my friend",
  "bitsMessage": "Thanks a lot for Bits {0}",
  "hostMessage": "Thanks a lot for the Host {0}",
  "raidMessage": "Raid Test",
  "donation": "donation test",
  "banChampWithBits": false,
  "activateFollowMessage": true,
  "activateSubscribeMessage": true,
  "activateBitMessage": true,
  "activateHostMessage": true,
  "activateRaidMessage": true,
  "activateDonationMessage": true,
  "donationMessage": "donation Test",
  "Zelda_AlertBox": true,
  "changeUI": "!ui",
  "UI_Position": "Top",
  "OauthToken": "OAuth xfm9bgudqadd53a5bfwqhm7gqw12l4",
  "runADCommand": "!ad",
  "ADInterval": 30.0,
  "titlePreset1": "Dia VI Jungler | !subtember",
  "gamePreset1": "League of Legends",
  "titlePreset2": "Arena | Everyone welcome",
  "gamePreset2": "Super Smash Bros. Ultimate",
  "titlePreset3": "Diamond  | TFT + LoL | Say hello",
  "gamePreset3": "League of Legends",
  "activateFollowGoal": true,
  "followerGoal": 10,
  "activateSubGoal": true,
  "subGoal": 1,
  "activateBitGoal": true,
  "bitGoal": 50,
  "activateDonationGoal": true,
  "donationGoal": 1,
  "donationBarCDTime": 180,
  "donationBarVisibleTime": 20,
  "donationBarActive": false,
  "donationVisibility": "Hidden"
};